package connection;

public enum MessageType {
    LOGIN,
    WRONG_INFO,
    ALREADY_LOGGED_IN,
    SIGN_UP,
    SIGN_UP_FAILED,
    CONNECTED,
    NEW_USER_CONNECTED,
    DISCONNECT,
    CHANGE_INFO,
    CHANGE_INFO_SUCCEEDED,
    CHANGE_INFO_FAILED,
    CHAT_TEXT,
    VOICE
}
